### ISSUE TITLE
Some URLs are not embedded in "Details are here!" text

### ISSUE THREAD

**Issue by furkansimsekli** [hacettepeoyt/hu-announcement-bot#15]
Latest example came from [Foreign Languages School](http://www.ydyo.hacettepe.edu.tr/tr), the URL is "_http://www.ydyo.hacettepe.edu.tr//tr/<img_src=fshacettepeedutrydyor-1034_"

I don't know why but there is a ```html``` tag here. It's totally unnecessary, because "_http://www.ydyo.hacettepe.edu.tr//tr/-1034_" leads to same page.

As you can see, the first one hasn't been rendered in GitHub too. It's an invalid URL.

This URL isn't produced because of my code, we can manually check the websites and see the ```href=""```

**Comment by melikechan** [comment]
My opinion is, it is an issue belongs to the _some departments_ those use _StandartDepartment_ class. 
I suppose that it can be solved by replacing the broken suffix with the extracted valid one.
