### ISSUE TITLE
BBY scraper seems working but sent odd announcements

### ISSUE THREAD

**Issue by furkansimsekli** [hacettepeoyt/hu-announcement-bot#32]
Yesterday there were two new announcements from them, titles weren't meaningful though.

1) `&s==encryptString(1);?>">=$duyuru["baslik_tr"];?>`
2) `&s==encryptString(1);?>">=$duyuru["baslik_eng"];?>`

I tried to regenarete the same thing manually this morning, but scraper didn't return such announcement :thinking:

**Comment by melikechan** [comment]
Well, I checked BBY's website and I can't see any new announcement either.

About the titles, well these seem like **PHP** codes.  (I think they are but you can take my claim with a pinch of salt 🤣 )

But I can't see any clues where the codes came from, maybe code _had experienced some bug or something like that..._

**Comment by melikechan** [comment]
By the way, is there anything happened related to this bug @furkansimsekli?

**Comment by furkansimsekli** [comment]
> By the way, is there anything happened related to this bug @furkansimsekli?

Nope, nothing new for now.

**Comment by furkansimsekli** [comment]
It was a one time thing apparently, problem haven't occured since then.
